openapi: 3.0.0
info:
  title: PlateShare Donation API
  description: API for managing donations within the PlateShare platform.
  version: 1.0.0
servers:
  - url: 'https://plateshare.com/api'
    description: Main API server
paths:
  /donations:
    post:
      summary: Make a donation
      description: Add a new donation with the given details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Donation'
            example:
              projectId: "123"
              donorId: "123e4567-e89b-12d3-a456-426614174001"
              type: "Food"
              qty: "10 boxes"
              donationAmountId:
                amount: "1000.00"
                currency: "USD"
      
      responses:
        '201':
          description: Donation created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Donation'
        '400':
          description: Bad request, details in error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /donations/{donationId}:
    put:
      summary: Update a donation
      description: Update the type and qty for an existing donation by its unique ID.
      parameters:
        - in: path
          name: donationId
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the donation to update.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: The new type of the donation.
                qty:
                  type: string
                  description: The new quantity of the donation.
              required:
                - type
                - qty
            example:
              type: "Clothes"
              qty: "5 bags"
      responses:
        '200':
          description: Donation updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Donation'
        '400':
          description: Bad request, validation errors or missing data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Donation not found with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Donation:
      type: object
      required:
        - projectId
        - donorId
        - type
        - qty
        - donationAmountId
      properties:
        donationId:
          type: string
          format: uuid
          description: Unique identifier for the Donation, auto-generated on creation.
        projectId:
          type: string
          format: uuid
          description: Unique identifier for the Project associated with the donation.
        donorId:
          type: string
          format: uuid
          description: Unique identifier for the Donor who made the donation.
        type:
          type: string
          description: The type of donation (e.g., Food, Clothes).
        qty:
          type: string
          description: The quantity of the donation.
        donationAmountId:
          $ref: '#/components/schemas/DonationAmount'
    DonationAmount:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          type: string
          format: float
          description: The amount of money donated, if applicable.
        currency:
          type: string
          description: The currency of the donated amount.
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Error code indicating the type of error.
        message:
          type: string
          description: A detailed message explaining the error.
